### ISSUE TITLE
Missing Locations & Data 

### ISSUE THREAD

**Issue by mwsasser** [AHeroicLlama/Mappalachia#6] opened 2021-01-26 14:55 UTC
First off, **thanks** for taking the time to create this tool.  It's fun!  But some locations that should be generating in the map aren't appearing.  

For instance, there should be an Acid Hard Point in a pond near the Pleasant Valley Station.  It's south-east of that station and north-east of the Beckwith Farm.

Is it possible there is a different Technical Name that isn't appearing?

Secondly -  To validate, does the tool use the current data from your client?

**Comment by AHeroicLlama** [comment] 2021-01-26 16:12
Hi @mwsasser it sounds like you've mapped `HardointAcidHazard` when you probably want to map `HardPointAcid01`. The 'hazard' entity is the trigger which causes your player to hurt when they walk over the acid. As this one is underwater I guess it doesn't have the trigger like the rest of the acid hardpoints would.

Does that solve your problem? Or is there anything else which you believe to be incorrect?
Otherwise I'll go ahead and close this issue.

And no, Mappalachia does not access your game install at all, it comes packaged with a pre-built database file assembled with the required data.

**Comment by mwsasser** [comment] 2021-01-27 18:11
Actually no, it's just not showing up.  I am indeed using `HardPointAcid01`, it's just not showing up.  Is it because it's hidden by a pool of water?

**Comment by AHeroicLlama** [comment] 2021-01-27 18:38
Heya @mwsasser Can you please share your outputted image which shows this one missing hardpoint please?

Also can you confirm we're talking about the same location in-game?
On the in-game map: https://i.imgur.com/8GqWJS3.png
In-person in-game: https://i.imgur.com/sPNafZZ.png
This is the same location as you described, south-east of Pleasant Valley station, in a pond north-east of Beckwith farm.

As you can see this location is correctly mapped by Mappalachia: https://i.imgur.com/BU1gbud.jpg

The fact that it's underwater should not affect it appearing on the map, and I'm not aware of any other technical name for hardpoints.

**Comment by mwsasser** [comment] 2021-01-27 19:01
![Mappalachia Map TEST](https://user-images.githubusercontent.com/7670483/106040203-beace300-609f-11eb-928e-48bc8429c64b.jpeg)

**Comment by AHeroicLlama** [comment] 2021-01-27 19:13
Thanks - so I can see what's going on but I can't explain why. If you compare your map with [mine](https://i.imgur.com/i2ofWEv.jpg). We can see on your map, all the plots including the legend key have been skewed towards the top left of the map (or 0,0) so in fact, every plot there is wrong.

Two possible causes come to mind - the image file `img\map_normal.jpg` has been tampered with, or you've actually made your own development build and adjusted the scaling values?

Can you please confirm you're using an unmodified release?

**Comment by mwsasser** [comment] 2021-01-27 19:22
I have not altered the files in any way.  In fact, I deleted the older directory and unzipped the new files into a folder on my desktop.  

I do use custom scaling in Windows Display settings, is the app compensating for that?

**Comment by AHeroicLlama** [comment] 2021-01-27 20:55
I can't reproduce this by changing the display scaling options in Windows on my own machine.

Could you please try and reduce your scaling to default just to verify if it is a cause?
Additionally do you use anything else (Any third party software or settings) which may adjust the sizing of images?

**Comment by mwsasser** [comment] 2021-01-27 21:44
I tried to change the dpi settings as well and nothing changed.  It's quite puzzling.  

We need more data to figure this out.  But I'm not sure what you'd need from me or someone else who has the same issue.

Does the app have a dependency or call something that might be affected by scaling?

**Comment by AHeroicLlama** [comment] 2021-01-27 23:14
Agreed, I haven't heard of anyone else with this issue.
It essentially exclusively uses the .net System.Drawing Namespace to do all the drawing and handling of any images.
I know this in turn uses GDI+ but I don't know much more than that.

All we can say for sure is it's not reproducible on every machine, and as far as we know is caused by something on your machine specifically.

Unfortunately without clear reproduction steps we might be at a dead end.
If you are able to identify with certainty what's causing it then I'd be happy to attempt a fix.

**Comment by mwsasser** [comment] 2021-01-28 00:41
I created another local account on my workstation.  It has no dpi scaling and Mappalachia worked perfectly in that account.  The nodes were in the right spot on the map.

So that probably does suggest it's probably dpi related.  I change those settings because of eyesight.  Maybe you'll eventually figure it out.  If so, let me know.  :-)

**Comment by AHeroicLlama** [comment] 2021-01-28 09:58
Okay thanks for your help, I was able to recreate this issue now. In Win10 settings > Display > 'Make everything bigger' > Set to 200% for example. On the Mappalachia shortcut > properties > compatibility > Change High DPI Settings > Override high DPI Scaling > Application.

This results in the plots drawn on the map being incorrectly not scaled, where the rest of the image is, causing all plots to be off by a factor equal to the zoom, tending towards the 0,0 coordinate.

I should be able to look into a fix for this, initial googling suggests System.Drawing can refer to the system 'graphics unit' when drawing, and may need to instead be changed to refer to absolute pixels, rather than a relative amount.

Thanks for the report and help @mwsasser
I'll update this when I have some more time to make a fix.

**Comment by AHeroicLlama** [comment] 2021-01-28 11:01
Fix pushed to development branch. Will look to release later today.

**Comment by AHeroicLlama** [comment] 2021-01-28 11:32
Resolved with release 1.0.5.0

**Closed by AHeroicLlama** 2021-01-28 11:32 UTC
